"""create_topic

Revision ID: 167c529ab94f
Revises: e805f685f771
Create Date: 2020-08-30 13:13:17.320555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167c529ab94f'
down_revision = 'e805f685f771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
