"""empty message

Revision ID: 2f729d6f6950
Revises: 88003262620e
Create Date: 2020-09-03 22:48:54.872364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f729d6f6950'
down_revision = '88003262620e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('mediaurl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'mediaurl')
    # ### end Alembic commands ###
